autocomplete = true
breaking_changes = true
issues = true
emoji = true

[[commit_types]]
name = "bugfix"
emoji = "ğŸ›"
description = "semantic PATCH version bump"

[[commit_types]]
name = "feature"
emoji = "âœ¨"
description = "semantic MINOR version bump"

[[commit_types]]
name = "style"
emoji = "ğŸ’„"
description = "styling or template changes"

[[commit_types]]
name = "test"
emoji = "ğŸš¨"
description = "adding, improving or correcting tests"

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "other and/or automated changes"

[[commit_types]]
name = "lang"
emoji = "ğŸ—£ï¸"
description = "changes to text content or languages translations"

[[commit_types]]
name = "refactor"
emoji = "ğŸ”¨"
description = "code improvements that don't change functionality"

[[commit_types]]
name = "build"
emoji = "ğŸ“¦"
description = "changes that affect the build system or external dependencies"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "goal-oriented guides, learning-orientated tutorials, information-orientated references, etc"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "changes to the CI/CD pipeline or deployment process"

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "performance improvements or debugging investigations"

[[commit_types]]
name = "revert"
emoji = "âª"
description = "undoing previously committed changes"
