edition = "2024"

## Whitespace
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

## Widths
max_width = 120
fn_call_width = 100
struct_lit_width = 40
struct_variant_width = 42
array_width = 72
chain_width = 110
single_line_if_else_max_width = 110
single_line_let_else_max_width = 80
# Calculate the maximum widths of various tokens
# as pre-defined percentages of max_width.
use_small_heuristics = "Default"

## Ordering
reorder_imports = true
reorder_modules = true

## Rewriting Code
remove_nested_parens = true
short_array_element_width_threshold = 10
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
match_block_trailing_comma = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
